### ISSUE TITLE
Chromium Bug

### ISSUE THREAD

**Issue by MichaelDavidGK** [return-true-if-false/discord-free-nitro-features#1]
Doesn't work on any chromium based browsers (majority)
![image](https://user-images.githubusercontent.com/39009683/193950494-334bce86-bffb-4686-ae0e-30db2a73d349.png)

**Comment by return-true-if-false** [comment]
This seems to be an issue in the userscript, can you try pasting the non-userscript js file and see if the issue still happens?

I'll let you know once I fix the userscript.

**Comment by return-true-if-false** [comment]
It should be fixed now, please follow the steps in the README again and let me know if you are having any other issues
