### ISSUE TITLE
Bugged replies

### ISSUE THREAD

**Issue by MichaelDavidGK** [return-true-if-false/discord-free-nitro-features#2]
Hi,
Since you fixed it recently it works now on chromium browsers, so thank you for that.
Hovewer I found another bug there (was there even before last fix).
When you try to reply to any message while script is activated then it won't count it as reply, will simply send message, not reply.

Would be nice if you could fix that as well ;)

**Comment by return-true-if-false** [comment]
AFAIK this should be an easy fix, I'll look into it now

**Comment by return-true-if-false** [comment]
This should be fixed now, please let me know if it still happens using newest version
